/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as DenemelerRouteImport } from './routes/denemeler'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as Index_newRouteImport } from './routes/index_new'
import { Route as KocRouteImport } from './routes/koc'
import { Route as KocGirisRouteImport } from './routes/koc-giris'
import { Route as KonuAgaciRouteImport } from './routes/konu-agaci'
import { Route as OdevlerRouteImport } from './routes/odevler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const DenemelerRoute = DenemelerRouteImport.update({
  id: '/denemeler',
  path: '/denemeler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const Index_newRoute = Index_newRouteImport.update({
  id: '/index_new',
  path: '/index_new',
  getParentRoute: () => rootRouteImport,
} as any)
const KocRoute = KocRouteImport.update({
  id: '/koc',
  path: '/koc',
  getParentRoute: () => rootRouteImport,
} as any)
const KocGirisRoute = KocGirisRouteImport.update({
  id: '/koc-giris',
  path: '/koc-giris',
  getParentRoute: () => rootRouteImport,
} as any)
const KonuAgaciRoute = KonuAgaciRouteImport.update({
  id: '/konu-agaci',
  path: '/konu-agaci',
  getParentRoute: () => rootRouteImport,
} as any)
const OdevlerRoute = OdevlerRouteImport.update({
  id: '/odevler',
  path: '/odevler',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/denemeler': typeof DenemelerRoute
  '/giris': typeof GirisRoute
  '/index_new': typeof Index_newRoute
  '/koc': typeof KocRoute
  '/koc-giris': typeof KocGirisRoute
  '/konu-agaci': typeof KonuAgaciRoute
  '/odevler': typeof OdevlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/denemeler': typeof DenemelerRoute
  '/giris': typeof GirisRoute
  '/index_new': typeof Index_newRoute
  '/koc': typeof KocRoute
  '/koc-giris': typeof KocGirisRoute
  '/konu-agaci': typeof KonuAgaciRoute
  '/odevler': typeof OdevlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/denemeler': typeof DenemelerRoute
  '/giris': typeof GirisRoute
  '/index_new': typeof Index_newRoute
  '/koc': typeof KocRoute
  '/koc-giris': typeof KocGirisRoute
  '/konu-agaci': typeof KonuAgaciRoute
  '/odevler': typeof OdevlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayarlar'
    | '/denemeler'
    | '/giris'
    | '/index_new'
    | '/koc'
    | '/koc-giris'
    | '/konu-agaci'
    | '/odevler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayarlar'
    | '/denemeler'
    | '/giris'
    | '/index_new'
    | '/koc'
    | '/koc-giris'
    | '/konu-agaci'
    | '/odevler'
  id:
    | '__root__'
    | '/'
    | '/ayarlar'
    | '/denemeler'
    | '/giris'
    | '/index_new'
    | '/koc'
    | '/koc-giris'
    | '/konu-agaci'
    | '/odevler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  DenemelerRoute: typeof DenemelerRoute
  GirisRoute: typeof GirisRoute
  Index_newRoute: typeof Index_newRoute
  KocRoute: typeof KocRoute
  KocGirisRoute: typeof KocGirisRoute
  KonuAgaciRoute: typeof KonuAgaciRoute
  OdevlerRoute: typeof OdevlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denemeler': {
      id: '/denemeler'
      path: '/denemeler'
      fullPath: '/denemeler'
      preLoaderRoute: typeof DenemelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index_new': {
      id: '/index_new'
      path: '/index_new'
      fullPath: '/index_new'
      preLoaderRoute: typeof Index_newRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koc': {
      id: '/koc'
      path: '/koc'
      fullPath: '/koc'
      preLoaderRoute: typeof KocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koc-giris': {
      id: '/koc-giris'
      path: '/koc-giris'
      fullPath: '/koc-giris'
      preLoaderRoute: typeof KocGirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konu-agaci': {
      id: '/konu-agaci'
      path: '/konu-agaci'
      fullPath: '/konu-agaci'
      preLoaderRoute: typeof KonuAgaciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odevler': {
      id: '/odevler'
      path: '/odevler'
      fullPath: '/odevler'
      preLoaderRoute: typeof OdevlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  DenemelerRoute: DenemelerRoute,
  GirisRoute: GirisRoute,
  Index_newRoute: Index_newRoute,
  KocRoute: KocRoute,
  KocGirisRoute: KocGirisRoute,
  KonuAgaciRoute: KonuAgaciRoute,
  OdevlerRoute: OdevlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
